# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fundü' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fundü

  pod 'SendBirdSDK'
  pod 'Charts'
  pod 'KYDrawerController'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'SCLAlertView', :git => 'https://github.com/vikmeup/SCLAlertView-Swift.git'
  pod 'PureLayout'
  pod 'JSQMessagesViewController'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  
  target 'fundüTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fundüUITests' do
    inherit! :search_paths
    # Pods for testing
  end




end
